# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lastdbupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameID',
        ),
        migrations.DeleteModel(
            name='LastDBUpdate',
        ),
    ]
