# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notgames_searchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-lastSearchDate', 'name']},
        ),
        migrations.RenameField(
            model_name='searchhistory',
            old_name='date',
            new_name='lastSearchDate',
        ),
    ]
